version: '2'

services:
    app:
        volumes:
            - ${HOME}/.aws:/opt/app/.aws:ro
        build:
            context: .
        ports:
            - 8080:8080
        environment:
            - AWS_REGION=us-west-2
            - AWS_PROFILE=default